export enum ExerciseCategory {
    CHEST = "chest",
    BACK = "back",
    LEGS = "legs",
    ARMS = "arms",
    SHOULDERS = "shoulders",
    CORE = "core",
    CARDIO = "cardio",
}

export const exercises = [
    {
        id: 1,
        name: "Bench Press",
        slug: "bench-press",
        desc: "A fundamental chest exercise that builds upper body strength.",
        image: require("../assets/images/bench-exercise-image.webp"),
        filter: ExerciseCategory.CHEST,
    },
    {
        id: 2,
        name: "Squat",
        slug: "squat",
        desc: "A powerful lower body exercise targeting legs and glutes.",
        image: require("../assets/images/squat-exercise.jpg"),
        filter: ExerciseCategory.LEGS,
    },
    {
        id: 3,
        name: "Deadlift",
        slug: "deadlift",
        desc: "A compound movement that engages the entire posterior chain.",
        image: require('../assets/images/deadlift-exercise.png'),
        filter: ExerciseCategory.BACK,
    },
    {
        id: 4,
        name: "Overhead Press",
        slug: "overhead-press",
        desc: "Strengthens shoulders and arms while improving core stability.",
        image: require('../assets/images/deadlift-exercise.png'),
        filter: ExerciseCategory.SHOULDERS,
    },
    {
        id: 5,
        name: "Pull-Up",
        slug: "pull-up",
        desc: "A bodyweight back exercise for building lats and grip strength.",
        image: require('../assets/images/deadlift-exercise.png'),
        filter: ExerciseCategory.BACK,
    },
    {
        id: 6,
        name: "Barbell Row",
        slug: "barbell-row",
        desc: "Targets the back and improves overall pulling strength.",
        image: require('../assets/images/deadlift-exercise.png'),
        filter: ExerciseCategory.BACK,
    },
    {
        id: 7,
        name: "Lunges",
        slug: "lunges",
        desc: "Improves balance and targets the quads and glutes.",
        image: require('../assets/images/deadlift-exercise.png'),
        filter: ExerciseCategory.LEGS,
    },
    {
        id: 8,
        name: "Bicep Curl",
        slug: "bicep-curl",
        desc: "Isolates the biceps for increased arm strength and size.",
        image: require('../assets/images/deadlift-exercise.png'),
        filter: ExerciseCategory.ARMS,
    },
    {
        id: 9,
        name: "Tricep Dips",
        slug: "tricep-dips",
        desc: "Targets the triceps and helps build upper arm definition.",
        image: require('../assets/images/deadlift-exercise.png'),
        filter: ExerciseCategory.ARMS,
    },
    {
        id: 10,
        name: "Plank",
        slug: "plank",
        desc: "A static core exercise improving endurance and stability.",
        image: require('../assets/images/deadlift-exercise.png'),
        filter: ExerciseCategory.CORE,
    },
];

export const exerciseFilters = [
    {
        id: 1,
        title: "Chest",
        label: ExerciseCategory.CHEST,
    },
    {
        id: 2,
        title: "Back",
        label: ExerciseCategory.BACK,
    },
    {
        id: 3,
        title: "Legs",
        label: ExerciseCategory.LEGS,
    },
    {
        id: 4,
        title: "Arms",
        label: ExerciseCategory.ARMS,
    },
    {
        id: 5,
        title: "Shoulders",
        label: ExerciseCategory.SHOULDERS,
    },
    {
        id: 6,
        title: "Core",
        label: ExerciseCategory.CORE,
    },
    {
        id: 7,
        title: "Cardio",
        label: ExerciseCategory.CARDIO,
    },
];
